@BASE_URL=http://host.docker.internal:8000
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMWE4OGU3OTYtZjIyYy00ZTQ2LWIxZDAtZTVhMzE1MDY0ZjYzIiwiZW1haWwiOiJ0ZXN0LmFzZEBnbWFpbC5jb20ifSwiaWF0IjoxNzA2Nzk3MDcwLCJleHAiOjE3MDY4MDA2NzAsInN1YiI6IjFhODhlNzk2LWYyMmMtNGU0Ni1iMWQwLWU1YTMxNTA2NGY2MyJ9.BFFZdKbtPZxr9DFMofHiBk7l0RAWwGq3EpXhuTJiQ74

GET {{BASE_URL}}/statistics/week/2024-02-01
Authorization: bearer {{TOKEN}}