version: '3.8'

services:
  devcontainer:
    container_name: wilt-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/backend:cached
    command: sleep infinity
    networks:
      - wilt-network

  db-dev:
    container_name: wilt-dev-db
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - wiltdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: wilt
      POSTGRES_DB: wilt-dev
    networks:
      - wilt-network
  
  db-test:
    container_name: wilt-test-db
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: wilt
      POSTGRES_DB: wilt-test
    networks:
      - wilt-network

networks:
  wilt-network:

volumes:
  wiltdb-data:
