name: Deploy to Azure

on:
  push:
    branches: main

jobs:
  deploy-image:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Azure Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME  }}
          password: ${{ secrets.ACR_PASSWORD  }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./app

      - name: Build and deploy image to ACR
        working-directory: ./app
        run: |
          docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/wilt-backend:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/wilt-backend:latest

  start:
    needs: deploy-image
    name: Start container
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start container
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wilt-backend:latest
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          containerAppName: wilt-backend
          location: "'Sweden Central'"
          environmentVariables: >
            DB_TYPE=secretref:dbtype
            DB_HOST=secretref:dbhost
            DB_PORT=secretref:dbport
            DB_USERNAME=secretref:dbusername
            DB_PASSWORD=secretref:dbpassword
            DB_NAME=secretref:dbname
            SALT_ROUNDS=secretref:saltrounds
            TOKEN_ALGORITHM=secretref:tokenalg
            TOKEN_SECRET=secretref:tokensecret
            TOKEN_EXPIRES_IN=secretref:tokenexpiresin
            REFRESH_TOKEN_EXPIRES_IN=secretref:expiresin
            ALLOWED_LOGIN_ATTEMPTS=secretref:allowedloginattempts
            LOGIN_BLOCK_DURATION=secretref:loginblockduration
            ALLOW_REGISTRATION=secretref:allowregistration
            CORS_ORIGINS=secretref:corsorigins
